### ISSUE TITLE
New Magnet Card client disconnection issue

### ISSUE THREAD

**Issue by LordofDorknes** [tracer4b/nomi-ceu#256]
**Pack Version:** 1.5.1

**Launcher:** Curseforge

**Mode:** Normal

**Description:**

After placing magnet card in new version of wireless terminal, client is disconnected and cannot reconnect. Every connection attempt ends in a ticking player exception.
**Expected Behavior:**
Wireless terminal crafting card should not disconnect player, nor prevent them from joining world.

**Steps To Reproduce:**

Bind wireless terminal to ME system, insert magnet card to wireless terminal.

**Crash Log:**
No crash log was generated, but the following traceback was generated on the server.
[15:07:05] [Server thread/WARN]: Failed to handle packet for /(IP Address)
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at appeng.items.tools.powered.ToolWirelessTerminal.magnetLogic(ToolWirelessTerminal.java:212) ~[ToolWirelessTerminal.class:?]
	at appeng.items.tools.powered.ToolWirelessTerminal.onUpdate(ToolWirelessTerminal.java:161) ~[ToolWirelessTerminal.class:?]
	at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
	at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[15:07:05] [Server thread/INFO]: (PlayerName) lost connection: Internal server error
**Screenshots:** N/A

**Comment by IntegerLimit** [comment]
known. https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/224 Can you paste the crash log there?

**Comment by LordofDorknes** [comment]
A new version of extended life AE2 (55.8) was uploaded to curseforge, looks like it should go in 1.5.2

**Comment by IntegerLimit** [comment]
Yeah, updating now.
